plugins {
    id 'java'
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'dev.oakheart'
version = '1.2.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "placeholderapi"
        url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
    }
    maven {
        name = "nexo-repo"
        url = "https://repo.nexomc.com/releases/"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.8-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("org.xerial:sqlite-jdbc:3.47.1.0")
    compileOnly("com.nexomc:nexo:1.20.0")
    compileOnly("com.github.LoneDev6:api-itemsadder:3.6.3-beta-14")
    implementation("org.bstats:bstats-bukkit:3.1.0")
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

compileJava {
    options.encoding = 'UTF-8'
    options.release = 21
    options.compilerArgs += ['-Xlint:deprecation', '-Xlint:unchecked']
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}

shadowJar {
    archiveClassifier.set('')
    relocate("org.bstats", "dev.oakheart.oaktags.bstats")
}

jar {
    archiveClassifier.set('slim')
}

tasks.assemble.dependsOn(tasks.shadowJar)
